Feature/ffwert
freifunkMUC/wgkex pull request #116
Opened 2023-11-25 07:44 UTC by istrator2

- I add support for multiple prefixes. Unique domains have to be used after the prefix.
- I fixed minor typos.
- My IDE did a lot of autoformatting.

I have no idea about docker, yml and other non python files, please double check them.
Maybe, more likely, something is missing.

2023-11-25 08:31 UTC, krombel approved these changes
Untested but I could not find issues through inspection.
LGTM

2023-11-25 08:35 UTC, krombel requested changes
Fix errors

2023-11-26 12:49 UTC, grische requested changes

2023-11-26 12:49 UTC, grische commented on .github/buildkitd.toml
> -  max-parallelism = 4
Ich glaube viele der Whitespace Änderungen sind unabsichtlich. Wäre besser wenn wir erst mal nichts an der CI ändern hier

2023-11-26 13:23 UTC, grische commented on .github/buildkitd.toml
> -  max-parallelism = 4
Thanks! @istrator2

2023-11-27 21:26 UTC, grische approved these changes

2023-11-27 21:27 UTC, istrator2 commented
@krombel @grische: I fixed everything you asked for.

2023-11-27 21:31 UTC, awlx approved these changes

2023-11-27 21:32 UTC, merged