Some fixes from FreifunkMYK
freifunkMUC/wgkex pull request #51
Opened 2021-08-14 09:44 UTC by awlx

Maybe we should have a look, as sadly there isn't a PR yet we maybe want to check for ourselves :).

2021-08-14 09:44 UTC, awlx commented
/cc @rucarrol-goog

2021-08-14 09:47 UTC, awlx commented on wgkex/worker/mqtt.py
> +    domain = re.search(r"^wireguard\/ff(\w+)\/", message.topic).group(1)
We need to make this a config option, otherwise this will be a mess.

2021-08-15 09:13 UTC, awlx commented on wgkex/worker/netlink.py
> +        stale_client for stale_client in find_stale_wireguard_clients("wg" + domain)
we need this hyphen ... maybe also something to add to configuration like "wg_interface_prefix"?

2021-08-15 16:21 UTC, rucarrol-goog requested changes

2021-08-15 16:21 UTC, rucarrol-goog commented on wgkex/worker/netlink.py
> +        return f"vx{self.domain}"
If we are changing the format here - we should be a bit careful, as we re-use this elsewhere. Could we consider putting these prefixes into the config file?

2021-08-17 18:30 UTC, krombel commented
This PR is based on the main branch of a fork. So this is just for reference. Features can be taken from here but this is probably never going to land directly in our main branch. Marking as draft therefore

2021-09-07 17:19 UTC, closed without merging